### ISSUE TITLE
Video Playback without the need of another tab.

### ISSUE THREAD

**Issue by CuddleBear92** [floogulinc/hydrus-web#11]
Video Playback without the need of another tab.

Want video playback on the main tab itself, in the carusel. 
Know this might be an issue, but still want it.

A site wide volume slider might be needed. Or the option to mute everything by default.

Also having looping as a default would be nice.

**Comment by floogulinc** [comment]
@CuddleBear92 I have done most of these things in #14. Please have a look and try it out.
