### ISSUE TITLE
Bug: cannot use Z key in any fields when viewing a file

### ISSUE THREAD

**Issue by hjri** [floogulinc/hydrus-web#111]
When viewing a file it's impossible to add a tag that has "z" in it, impossible to enter letter "z" when adding notes either. Only lowercase z is affected (i.e. shift-z works), seemingly the only keycode is affected, so pressing `z` with say, cyrillic layout would type "я" but it's not typed either. This seemingly only affects fields within image viewer, but not ones in the rest of the UI, i.e. you can still search tags that contain "z" just fine. Affects both Chromium and Firefox, doesn't seem to be related to any browser extensions. Nothing interesting in console when i press `z`. Could be a PhotoSwipe bug.

**Comment by floogulinc** [comment]
Thanks for the report. I have fixed this issue.
