### ISSUE TITLE
Error when downloading large fiels

### ISSUE THREAD

**Issue by AquaSZS** [floogulinc/hydrus-web#128]
Downloading large files (mp4 files >100 MB) encounters `Error downloading file: Http failure response for https://....duckdns.org/get-files/file?hash=... 0 Unknown Error` on latest dev version (1.1.0).

**Comment by floogulinc** [comment]
Can you please provide what device and browser you're using. This may be unavoidable because due to cross origin limitations I cannot just tell the browser to directly download the file but have to save it to ram before having the browser download it.

**Comment by floogulinc** [comment]
This will probably be fixed when https://github.com/hydrusnetwork/hydrus/issues/1375 is done in hydrus and I can have it directly download from the API.

**Comment by AquaSZS** [comment]
Android Firefox on Galaxy Note 5. As you suspect, memory limits might be the culprit.

**Comment by floogulinc** [comment]
Ah yeah that probably is it. Well, until the feature I requested is added to Hydrus you can hold on "open file in new tab" from the menu in the file info card and select "download link".

**Comment by floogulinc** [comment]
This has now been fixed on the dev branch if you're running Hydrus 532 or newer.
