### ISSUE TITLE
504 Gateway Timeout when SSL used

### ISSUE THREAD

**Issue by KamillaPup** [floogulinc/hydrus-web#130]
I'm trying to use Hydrus Web and it works locally with non-SSL but it doesn't work on another device on the same network. I read it has to be SSL to connect from another client on the network, but SSL gives the error:
```Error searching: Http failure response for https://127.0.0.1:45869/get_files/search_files?tags=%5B%5D&file_sort_type=2&file_sort_asc=false&return_file_ids=true&return_hashes=false: 504 Gateway Timeout```
What can I do to make this work? Do I need to make a self-signed certificate… but can I do that for an IP or do I need to assign one to my computer?

MacBook Studio
MacOS 13.4.1 (22F82)
Hydrus v540

I do have a QNAP NAS and could put Docker in a container but I think that would be rather inconvenient.

My end goal is to use Hydrus Web outside the network to edit tags and such remotely.

**Comment by floogulinc** [comment]
Due to how browser security works your Hydrus API needs to have a valid https certificate. I recommend following this guide and using tailscale to access the API with valid https from anywhere: https://github.com/floogulinc/hydrus-web/wiki/Accessing-the-Hydrus-API-with-Tailscale-Serve
