### ISSUE TITLE
Latest Client and API update breaks

### ISSUE THREAD

**Issue by bramnet** [floogulinc/hydrus-web#156]
The latest version of Hydrus' client is 565 and the API is 62. I recently did a upgrade to this version (jumped multiple versions so I don't know which version of the client or API broke this functionality) and now whenever the site tries to complete any query, an Unknown Error occurs which appears to be acting as if no access key was passed through the API. If I visit the site in the error manually, it loads the results with no problems.
What currently happens according to the site.
```
{
  "headers": {
    "normalizedNames": {},
    "lazyUpdate": null,
    "headers": {}
  },
  "status": 0,
  "statusText": "Unknown Error",
  "url": "http://localhost:45869/get_files/search_files",
  "ok": false,
  "name": "HttpErrorResponse",
  "message": "Http failure response for http://localhost:45869/get_files/search_files: 0 Unknown Error",
  "error": {
    "isTrusted": true
  }
}
```
What returns when I go to http://localhost:45869/get_files/search_files?Hydrus-Client-API-Access-Key={Access-Key}
``{"file_ids": [], "version": 62, "hydrus_version": 565}``

**Comment by bramnet** [comment]
I should've thought of this ahead of time, but everything is working just fine on https://hydrus.app/. I'll try and investigate this further.

**Comment by bramnet** [comment]
OK, never mind. Apparently a chrome update broke it because this is working fine with all of my other browsers.

**Comment by floogulinc** [comment]
Valid https for your Hydrus API is usually required. Browsers have in the past had an exception for localhost but that may not be the case forever. I recommend following one of the guides in the wiki.
