### ISSUE TITLE
Add filename tag (new files only) option is grayed out

### ISSUE THREAD

**Issue by DSGMods** [floogulinc/hydrus-web#160]
Got Hydrus Web up and running in docker talking to the client container, all on the same machine over HTTP. I can upload images but I can't check the option to add filename as a tag. Is there an option in the client or in Hyddus Web I need to enable or does this require HTTPS?

![image](https://github.com/floogulinc/hydrus-web/assets/50091859/ba7b13bc-41a6-49f6-bacc-5387ec6ed0f2)

Some other information:
Hydrus Web 1.3.0
Hydrus Client 579
Client API 64

**Comment by floogulinc** [comment]
You need to select a tag service to use for the filename tags in the settings.

**Comment by DSGMods** [comment]
All good now, thanks.
