### ISSUE TITLE
Feature Request: Allow restricting searched to archive/inbox only

### ISSUE THREAD

**Issue by propeeves** [floogulinc/hydrus-web#24]
I'd like to be able to search only archived posts when searching tags - currently this isn't possible.

**Comment by floogulinc** [comment]
This has been added in https://github.com/floogulinc/hydrus-web/commit/9057ca7936eb4eb1ee9706df2dcfc2c737ad98c3 on the `dev` branch.

**Comment by floogulinc** [comment]
This has now been incorporated into `master`.
