### ISSUE TITLE
Tag exclusion autocomplete

### ISSUE THREAD

**Issue by Suika** [floogulinc/hydrus-web#29]
Short gist of it is: It should be possible to start typing `-` and then have the application autocomplete the tags after that.
Example: Start typing `-dou` and `medium:doujinshi` would show up. If that tag is selected, the `-` will be prepended and the endresult would be `-medium:doujinshi`

Hydrus supports tag exclusion via the API and it is possible to write out the exclusion in the tag field of hydrus web, but it's still a pain to do on bigger/more tags without auto completion.

**Comment by floogulinc** [comment]
I have added this and it should be live in the `dev` branch.

**Comment by Suika** [comment]
Works
