### ISSUE TITLE
feature request: display URLs for images

### ISSUE THREAD

**Issue by puphime** [floogulinc/hydrus-web#32]
I'd like for the urls added to images in hydrus (like the danbooru url, pixiv url, etc) to be visible (perhaps in the file info popup)

**Comment by floogulinc** [comment]
This is the current behavior in the `dev` version. I'm kinda behind on releasing new regular versions so if you want the latest features and fixes its recommended to use the `dev` version.

<img src="https://user-images.githubusercontent.com/1300395/93584792-6afcf100-f96b-11ea-9cd6-f4b171573faa.png" width="50%">

**Comment by puphime** [comment]
oh! cool, thank you
