### ISSUE TITLE
option for saucenao api key

### ISSUE THREAD

**Issue by kotonbu** [floogulinc/hydrus-web#34]
having the option to add your saucenao api key for the lookup on the send page would be a nice feature for people with premium account's so they can lookup more images without being rate limited.

**Comment by floogulinc** [comment]
I agree, this is a planned feature once I get a new settings system together. I also want to allow users to enter a CORS proxy to use rather than just using the demo https://cors-anywhere.herokuapp.com/.

**Comment by floogulinc** [comment]
Saucenao is back in the dev branch and you can (and need to) provide an API key.
