### ISSUE TITLE
Selfsigned Certificates don't work

### ISSUE THREAD

**Issue by Ryonez** [floogulinc/hydrus-web#36]
Enabling https in hydrus cause it to create a self signed certificate. This does not work with Firefox for `https://hydrus.app/`.

The error returned:
```
GET https://127.0.0.1:45869/verify_access_key net::ERR_CERT_AUTHORITY_INVALID
```

**Comment by floogulinc** [comment]
This is expected. The browser doesn't allow invalid certificates. As it says in the readme, "you will need to make its API available with valid HTTPS". The default Hydrus self signed certificate does not do this. You need to either setup a reverse proxy that can provide valid HTTPS, for example using Caddy, or setup a self-signed CA which you can install on your devices and use to issue a certificate for the Hydrus API to use, see https://github.com/hydrusnetwork/hydrus/issues/675

**Comment by Ryonez** [comment]
Understood, thank you for letting me know.
