### ISSUE TITLE
[Feature Request] file_sort_type and file_sort_asc support for browsing files.

### ISSUE THREAD

**Issue by river58** [floogulinc/hydrus-web#49]
Reading through the hydrus client API, it seems to support extra arguments being passed to the search for file_sort_type and file_sort_asc, which changes the method the results are sorted. I'm wondering if support for changing the sorting method and direction could be added to the web client, as it would make it easier to manage larger sets of images, or find specific things. 

Could probably add a specific sort button near the filter button, or even include this in the same filter button.
Or even just add a custom tag for specifying order: 

If not adding all of them, at the very least, it would be quite useful to have access to ordering by filesize, date imported (default), duration, random, has audio, number of frames.

**Comment by floogulinc** [comment]
This is a fairly recent addition to the Hydrus API but yes I do plan to add sorting.

**Comment by floogulinc** [comment]
This was added a bit ago on the dev branch.
