### ISSUE TITLE
Support for OR tag searching

### ISSUE THREAD

**Issue by mruac** [floogulinc/hydrus-web#55]
The Hydrus client api now supports OR tag searching, as seen [here](https://github.com/hydrusnetwork/hydrus/issues/854) and the formatting style can be found [here](https://hydrusnetwork.github.io/hydrus/help/client_api.html#get_files_search_files).
```
Also, OR predicates are now supported! Just nest within the tag list, and it'll be treated like an OR. For instance:

[ "skirt", [ "samus aran", "lara croft" ], "system:height > 1000" ]
Makes:
skirt
samus aran OR lara croft
system:height > 1000
```

Not sure what your preference on stringing tags together to create an OR query, maybe these might inspire you:

- User long-presses to select tags to be added into an OR query
- User drags tags to the left of the tag search field into a `+` icon to build an OR query, then taps on the `+` icon to add the OR query to the search results.
- Just enter `OR` in capitals to count the tags next to the `OR` as an OR query. eg. `samus aran OR lara croft OR chun-li`

**Comment by floogulinc** [comment]
OR searching has been added on the dev branch.
