### ISSUE TITLE
Sort order, file limit and password protection.

### ISSUE THREAD

**Issue by MediaMoots** [floogulinc/hydrus-web#65]
Hi!

Thanks so much for making this app, it works amazingly!

After using it for a while I found a few things that could be improved to make it even more amazing:
It would be great if we could sort the files
https://hydrusnetwork.github.io/hydrus/developer_api.html#get_files_search_files
`file_sort_type`
For example, sort by random so that we get different images each time.

Also, if we could customize the number of files got each time that would also be cool. (Now it gets just 96 files per scroll request)

Another feature that would be great is a simple PIN or password authentication before accessing the website when run locally (e.g., Docker)
For now, I can just add a simple auth to nginx but it would be nice if it were built in.

Thanks!

**Comment by floogulinc** [comment]
Your first two suggestions are definitely planned features. As for the idea of a pin or password for Hydrus Web, I'm not quite sure what you're asking for. Hydrus Web already requires your API key be entered to access anything. There is no reason to try to restrict access to Hydrus Web itself even when self-hosted.

**Comment by floogulinc** [comment]
I think you misunderstand how Hydrus Web works. The Hydrus Web docker container or hydrus.app doesn't connect to your Hydrus client. Only your browser connects to your Hydrus client API. It stores the API key in the browser local storage. So there is no need to secure access to Hydrus Web itself. 

If you're concerned about someone with access to the device you use Hydrus Web on, any password or pin controlling access to Hydrus Web itself provides no true security as one could still get the API key from the browser  storage and directly connect to your Hydrus client API.

If you just want to casually prevent someone from just stumbling on what you have in hydrus then yeah something like what you did would work. I might consider a non-secure password lock similar to the Hydrus client for this usecase but its not high priority.

**Comment by MediaMoots** [comment]
![56642ABB-3FEC-4790-A217-64C5B9F54668](https://user-images.githubusercontent.com/81146974/187566498-f76b6b06-9352-4e66-8d6d-7b5cb1dff508.jpeg)

Also, there's this issue where when using the docker version, the hash causes the ui to overflow.

**Comment by floogulinc** [comment]
Haha. I don't test the Docker build very often. Apparently my script to grab the got branch is returning that in the GitHub Actions build.

**Comment by floogulinc** [comment]
Quick update, sorting has been added on the dev branch and I think I've fixed that issue with the docker branch name in the top bar.

**Comment by MediaMoots** [comment]
Thank you! It works great, would it be possible to save the sort order between sessions?

**Comment by floogulinc** [comment]
v1.0.0 has added sorting to the stable version. Please make new separate issues for your other requests.

**Comment by MediaMoots** [comment]
Wow, amazing thank you so much!
