### ISSUE TITLE
The ability to edit tags/urls

### ISSUE THREAD

**Issue by ShadowJonathan** [floogulinc/hydrus-web#68]
(From hydrus #general; @floogulinc wants to make this a feature)

The ability to add, edit, or remove tags and URLs from the web interface. This'd basically make it a lightweight hydrus interface to start tagging with.

**Comment by floogulinc** [comment]
In the dev branch now you can add and delete tags from local tag services

**Comment by ShadowJonathan** [comment]
I can't seem to use it on dev.hydrus.app because the edit toggle is greyed out. The api token has all permissions, what else do I need to enable/change?

**Comment by floogulinc** [comment]
@ShadowJonathan I forgot to mention you need to be running at least Hydrus 506 (507 to see "all known tags").

**Comment by ShadowJonathan** [comment]
Alright yeah, I can confirm the ability to edit tags with 507, but not URLs

**Comment by floogulinc** [comment]
Personally editing URLs isn't something I would almost ever do but if there are people would want that functionality it shouldn't be too hard to add.
