### ISSUE TITLE
Unable to connect to API server using DuckDNS

### ISSUE THREAD

**Issue by horribleCodes** [floogulinc/hydrus-web#70]
I followed the guide in the wiki, but I still can't reach the API server of my Hydrus Network. So far I've:
- Enabled client API (changed port to `7869`, I can access it with `localhost:7869`)
- Set up a Tailscale account & started it (I can ping it)
- Set up a Duck DNS account & created a new subdomain
- Updated the IPv4 of the subdomain with the Tailscale IP (`100.x.y.z`) of my PC
- Downloaded `caddy.exe` with Duck DNS support and `WinSW-x64`. (renamed to `caddy-service.exe`)
- Created `caddy-service.xml`, filled it with the following:
```xml
<service>
  <id>caddy</id>
  <!-- Display name of the service -->
  <name>Caddy Web Server (powered by WinSW)</name>
  <!-- Service description -->
  <description>Caddy Web Server (https://caddyserver.com/)</description>
  <executable>%BASE%\caddy.exe</executable>
  <arguments>run</arguments>
  <log mode="roll-by-time">
    <pattern>yyyy-MM-dd</pattern>
  </log>
</service>
```
- Created `Caddyfile`, filled it with the following:
```
https://DOMAIN.duckdns.org {
	reverse_proxy localhost:7869
	tls MAIL {
		dns duckdns KEY
	}
	encode zstd gzip
}

```
- Started the Caddy service using Services and executed `caddy.exe -reload` in the caddy directory

After all these steps, visiting my Duck DNS subdomain has led to various results. Sometimes it is unresponsive, sometimes it brings me to the default nginx page (I don't know why, I don't have it running), but currently it is showing me the Hydrus client API site after I used `caddy.exe -reload` despite not having changed `Caddyfile` or `caddy-service.xml`. And though the correct page is shown,, I still can't connect hydrus.app with my API URL and key:
```
Error: Http failure response for htps://horihydrus.duckdns.org/verify_access_key: 0 Unknown Error
```
Looking at the Debugger, it seems I am being redirected from port `80` to `443` - shouldn't it be `7869`? I also could successfully verify my access key by sending a REST request directly.
What exactly takes care of updating the IP of my domain on Duck DNS in this process?

**Comment by floogulinc** [comment]
Looking at the error it seems you missed a letter: `htps://horihydrus.duckdns.org/verify_access_key`. it should start with `https`.

**Comment by floogulinc** [comment]
> Looking at the Debugger, it seems I am being redirected from port 80 to 443 - shouldn't it be 7869?

Your hydrus API is at 7869 but caddy is running on 443 (the default https port) and proxying requests to 7869 while handling the https certificate and such.


> What exactly takes care of updating the IP of my domain on Duck DNS in this process?

If you're using Tailscale, the Tailscale IP of the machine is static and won't change so it doesn't need to be updated on DuckDNS.

**Comment by horribleCodes** [comment]
Boy, do I have egg on my face now. thanks for pointing that out, it works now.
On a similar note, is it possible to specify a port in the API URL? Entering the port with `:7869` didn't work with Hydrus Web, but maybe there is some way I could connect with `https://domain.duckdns.org/hydrus`?

**Comment by floogulinc** [comment]
Is there a reason you don't want to use port 443? You can change the port in the Caddyfile by changing the url at the top to include the port for example `https://DOMAIN.duckdns.org:1234` but there isn't much reason to unless you need port 443 for some other program.

**Comment by horribleCodes** [comment]
I would have liked to do just that, yes.
In any case, since my isssue has been resolved, I'll close it now.
