### ISSUE TITLE
File metadata not showing

### ISSUE THREAD

**Issue by mruac** [floogulinc/hydrus-web#91]
When clicking on the ⓘ button, the file metadata (known urls, tags, dimensions, etc) does not load. The site dims to attempt show it, but it doesn't load.

I suspect this may be due to the update in the client API with the way how the metadata is presented. I'm currently updating my tagging up to work with it too.

**Comment by floogulinc** [comment]
If you're running a recent version of Hydrus please use the dev branch of Hydrus Web for now (https://dev.hydrus.app/).

**Comment by mruac** [comment]
Yep, that's it. Cheers!
